from distutils.core import setup, Extension

setup(name='VMIutils',
      version='0.1',
      description='Programs for inverting VMI image',
      author='Jonathan G. Underwood',
      author_email='j.underwood@ucl.ac.uk',
      packages=['vmiutils',
                'vmiutils.pbasex',
                'vmiutils.pbasex.detfn1',
                'vmiutils.ChoNa',
                'vmiutils.simulate',
            ],
      ext_modules=[Extension('vmiutils.pbasex._matrix', 
                             ['vmiutils/pbasex/_matrix.c'],
                             libraries=['gsl', 'gslcblas', 'm']),
                   Extension('vmiutils.pbasex.detfn1._matrix_detfn1',
                             ['vmiutils/pbasex/detfn1/_matrix_detfn1.c'],
                             libraries=['gsl', 'gslcblas', 'm']),
                   Extension('vmiutils.pbasex.detfn1._fit_detfn1',
                             ['vmiutils/pbasex/detfn1/_fit_detfn1.c'],
                             libraries=['gsl', 'gslcblas', 'm']),
                   Extension('vmiutils.pbasex._fit',
                             ['vmiutils/pbasex/_fit.c'],
                             libraries=['gsl', 'gslcblas', 'm']),
                             ],
      scripts=['scripts/pbmatrix',
               'scripts/pbmatrix_detfn1',
               'scripts/pbfit',
               'scripts/pbfitplt',
               'scripts/cnfit',
               'scripts/vmiview',],
      )
