#!/usr/bin/python

import argparse
import logging
import numpy
import vmiutils as vmi
import vmiutils.pbasex as pb

logging.basicConfig()
logger = logging.getLogger('pbfit')

parser = argparse.ArgumentParser(
    description='Utility for inverting a VMI image using a PBASEX matrix')

parser.add_argument('vmi_file', help='Name of file containing VMI image')
parser.add_argument('matrix_file', help='Name of file containing PBASEX matrix')

args = parser.parse_args()

mtx = pb.PbasexMatrix()
mtx.load(args.matrix_file)
print 'here1'

vmicart = vmi.VMICartesianImage()
vmicart.from_numpy_array(numpy.loadtxt(args.vmi_file))
print 'here1a'

centre = vmicart.centre_of_gravity()
print centre
vmicart.set_centre(centre)
print 'here2'

vmipolar = vmi.VMIPolarImage()
vmipolar.from_VMICartesianImage(vmicart, Rbins=mtx.Rbins, Thetabins=mtx.Thetabins)
print 'here3'

fit = pb.PbasexFit()
fit.fit_data(vmipolar, mtx)

r, i = fit.calc_radial_spectrum(500)

#import pylab
#pylab.figure()
#pylab.plot(r, i)
#pylab.show()

r, theta, dist = fit.calc_distribution()

pylab.figure()
pylab.imshow(dist, cmap=pylab.cm.gist_gray)
pylab.show()
