#!/usr/bin/python

# Copyright (C) 2014 by Jonathan G. Underwood.
#
# This file is part of VMIUtils.
#
# VMIUtils is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# VMIUtils is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with VMIUtils.  If not, see <http://www.gnu.org/licenses/>.

import numpy
import matplotlib
import matplotlib.pyplot as plot
from matplotlib.widgets import Cursor
from mpl_toolkits.axes_grid1 import make_axes_locatable
import argparse
import sys

parser = argparse.ArgumentParser(
    description='Simple utility for examining a VMI data file and locating the centre of an image')

parser.add_argument('vmifile', help='Name of file containing VMI data')
parser.add_argument('--delimiter', default=None,
                    help='Specifies the delimiter used (defaults to whitespace)')

args=parser.parse_args()

try:
    if args.delimiter is not None:
        data = numpy.loadtxt(args.vmifile, delimiter = args.delimiter)
    else:
        data = numpy.loadtxt(args.vmifile)
except IOError:
    print('could not read file: {0}'.format(args.vmifile))
    sys.exit(74)

fig = plot.figure()
ax = fig.add_subplot(111, axisbg='#FFFFCC')
im = ax.pcolormesh(data.T, cmap=matplotlib.cm.spectral)
ax.axis('image')
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.05)
plot.colorbar(im, cax=cax)
cursor = Cursor(cax, useblit=True, color='red')#, linewidth=2)

plot.show()
